import { FriendsProvider } from "@/hooks/useFriends";
import "./globals.css";
import { Nav } from "@/Components/Nav";
import { Friend } from "@/types";
import { getFromFile } from "@/lib/utils";
import { Providers } from "./providers";
const getFriends = async (): Promise<Friend[]> => {
  return await getFromFile<Friend[]>("data/friendsjson.json");
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const friends = await getFriends();

  return (
    <html lang="en">
      <body className="bg-gray-600 ">
        <FriendsProvider baseFriends={friends}>
          <Providers>
            <Nav />
            <div className="max-w-6xl m-auto">{children}</div>
          </Providers>
        </FriendsProvider>
      </body>
    </html>
  );
}
