import { FriendsProvider } from "@/hooks/useFriends"
import "./globals.css"
import { Nav } from "@/Components/Nav"
import { Friend } from "@/types"
import { getFromFile } from "@/lib/utils"
import { UserProvider } from "@/hooks/useUser"
const getFriends = async (): Promise<Friend[]> => {
	return await getFromFile<Friend[]>("data/friendsjson.json")
}

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const friends = await getFriends()

	return (
		<html lang="en">
			<body className="bg-zinc-600 ">
				<UserProvider>
					<FriendsProvider baseFriends={friends}>
						<Nav />
						<div className="max-w-6xl m-auto">{children}</div>
					</FriendsProvider>
				</UserProvider>
			</body>
		</html>
	)
}
